class TransactionPool:
    """Will track all of the transactions in the blockchain
    """

    def __init__(self) -> None:
        self.transaction_map = {}

    def set_transaction(self, transaction):
        """This will add the transaction to the transaction map or update it if it already exists in there

        Args:
            transaction (object): tranaction object that is to be added to the pool
        """
        self.transaction_map[transaction.id] = transaction

    def existing_transaction(self, address):
        """Will find a trnasaction generated by the address in the transaction pool

        Args:
            address (string): sender wallet's address
        """
        for transaction in self.transaction_map.values():
            if transaction.input['address'] == address:
                return transaction